name = "backend"
main = "src/index.ts"
compatibility_date = "2024-11-20"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDEzMTI3MjItZGMyYi00MGQ5LWFjMDAtM2E0MGFmMTJiMWJmIiwidGVuYW50X2lkIjoiZmU0N2U4MTM1NjAxNjY4OWY2NTBkYjUxZWU0MDE1ZWJiYjNlNTFmNzFiYWFmZDBiNGZhNjIyODVhZTIyODI4NiIsImludGVybmFsX3NlY3JldCI6IjAzM2VmZWY2LTkxYjItNDExMy1iZDJjLTQ0ZDcyOTI0ZGVhMCJ9.B0p7ptwEpcXDY9XBeDewd-yohCiM7M95aWaaYUqoxDo"


# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1